version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    networks:
      - dev
    environment:
      discovery.type: single-node

  dem_dev:
    build:
      context: .
    environment:
      DJANGO_SETTINGS_MODULE: tests.settings
    depends_on:
      - elasticsearch
    volumes:
      - ./:/code:cached
    networks:
      - dev

networks:
  dev:
    driver: bridge
