name: test_djelme

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-py
        with:
          python-version: '3.7'
      - run: pip install .[dev]
      - name: alias pythonX.Y for tox
        run: alias python${{ steps.setup-py.outputs.python-version }}=${{ steps.setup-py.outputs.python-path }}
      - run: TOXENV=lint tox


  test:
    strategy:
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10']
        django: ['1.11', '2.0', '2.1', '2.2', '3.0', '3.1', '3.2', '4.0', '4.1']
        # TODO: elasticsearch: ['6', '7', '8', '9', ...
        exclude:
          - {python: '3.7', django: '4.0'}
          - {python: '3.7', django: '4.1'}
          - {python: '3.10', django: '1.11'}
          - {python: '3.10', django: '2.0'}
    runs-on: ubuntu-latest
    container: python:${{matrix.python}}-slim
    services:
      elasticsearch7:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
        env:
          discovery.type: single-node
    env:
      ELASTICSEARCH_HOST: elasticsearch7:9200
    steps:
      - uses: actions/checkout@v3
      - run: pip install .[dev]
      - run: TOXENV=`echo 'py${{matrix.python}}-django${{matrix.django}}' | sed 's/\.//g'` tox

